service: aws-guardduty-opsgenie-alerter # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
  stage: prod
  region: us-west-2


package:
 exclude:
   - ./**
 include:
   - ./bin/**

#Give your function a name, mine was "event_listener"
functions:
  event_listener:
    handler: bin/listener

    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.guardduty"
            detail-type:
              - "GuardDuty Finding"
            detail:
              severity: [ 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9 ]
# GuardDuty severity levels defined here:
# https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings.html#guardduty_findings-severity
# THIS TEMPLATE IS CONFIGURED TO FIRE A LAMBDA EVENT FOR EVERY MEDIUM AND HIGH RISK ISSUE FOUND, USE THE ABOVE LINK
# TO CONFIGURE YOUR ENVIRONMENT FOR YOUR OWN RISK TOLERANCE

# ADJUST THIS TO HAVE YOUR API KEY AND TEAM NAME/ID
# THESE CAN BE FOUND HERE: https://app.opsgenie.com/teams/dashboard/c74d89c3-45e0-4677-b26e-61639a1478e6#/
# https://app.opsgenie.com/integration
    environment:
      OPSGENIE_API_KEY:
      TEAM_ID:
      TEAM_NAME:
