service: aws-guardduty-opsgenie-alerter # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
  stage: prod
  region: us-west-2


package:
 exclude:
   - ./**
 include:
   - ./bin/**

#Give your function a name, mine was "event_listener"
functions:
  event_listener:
    handler: bin/listener

# ADJUST THIS TO HAVE YOUR API KEY AND TEAM NAME/ID
# THESE CAN BE FOUND HERE: https://app.opsgenie.com/teams/dashboard/c74d89c3-45e0-4677-b26e-61639a1478e6#/
# https://app.opsgenie.com/integration
    environment:
      OPSGENIE_API_KEY:
      TEAM_ID:
      TEAM_NAME:
